name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update apt
      run: sudo apt update
    - name: Install CSFML
      run: sudo apt install libcsfml-dev
    - uses: actions/checkout@v4
    - name: compiling Code
      run: gcc -o my main.c -lcsfml-graphics -lcsfml-window -lcsfml-system
